import type { CandidateInterviewRole } from "@/lib/store";

export type InterviewQuestion = {
  questionIndex: number;
  question: string;
};

const ROLE_QUESTION_BANK: Record<CandidateInterviewRole, string[]> = {
  Engineering: [
    "Tell us about a system you built end to end and the trade-offs you made.",
    "How do you debug a production issue when the root cause is unclear?",
    "Describe a time you improved performance or scalability in an application.",
    "How do you decide between shipping quickly and improving code quality?",
    "Walk us through a technical design you led from idea to deployment.",
    "How do you handle disagreements during code review?",
    "What metrics or signals do you watch after releasing a feature?",
    "Describe a time you had to work with a legacy codebase.",
    "How do you make your code easy for another engineer to maintain?",
    "Tell us about a difficult bug you solved and how you confirmed the fix.",
    "How do you approach testing for a critical feature?",
    "Describe a time you had to learn a new technology quickly.",
    "How do you keep user data and system design secure?",
    "What would you do if you missed a delivery date on an important project?",
    "How do you collaborate with product and design partners on requirements?",
    "Describe a time you took ownership of an ambiguous problem.",
    "How do you estimate engineering work when the scope is not fully known?",
    "What is your approach to observability and monitoring?",
    "Describe a situation where you had to mentor or unblock another engineer.",
    "Why is this engineering role the right next step for you?",
  ],
  Product: [
    "Tell us about a product decision you made using data and customer feedback.",
    "How do you prioritize between competing feature requests?",
    "Describe a time you had to influence stakeholders without direct authority.",
    "How do you define success for a new product or feature launch?",
    "Walk us through how you would validate a new product idea.",
    "How do you balance user needs, business goals, and engineering constraints?",
    "Describe a time you changed your roadmap because of new information.",
    "How do you investigate why users are dropping off in a flow?",
    "What metrics would you track after shipping an important feature?",
    "Tell us about a product experiment that changed your thinking.",
    "How do you gather and synthesize feedback from different teams?",
    "Describe a time you had to say no to a request and explain why.",
    "How do you manage ambiguity when the problem statement is not clear?",
    "What makes a product requirement ready for engineering handoff?",
    "How do you think about pricing, packaging, or monetization trade-offs?",
    "Describe a time you shipped something that did not work as expected.",
    "How do you decide when a feature should be simplified or removed?",
    "What does a strong product partnership with design and engineering look like?",
    "Describe your approach to roadmap planning over the next quarter.",
    "Why are you interested in product work for this role?",
  ],
  Design: [
    "Tell us about a design project you owned from research to delivery.",
    "How do you turn user feedback into a better interface?",
    "Describe a time you had to defend a design decision with evidence.",
    "How do you balance visual polish with usability and speed?",
    "Walk us through your process for solving a messy user problem.",
    "How do you collaborate with engineers when feasibility changes a design?",
    "What do you look for in usability testing or prototype feedback?",
    "Describe a time you simplified a complicated flow.",
    "How do you think about accessibility in your day-to-day design work?",
    "Tell us about a design that performed better than expected.",
    "How do you decide what should be fixed first in a mature product?",
    "Describe a time you worked with limited information or vague requirements.",
    "How do you maintain consistency across a product experience?",
    "What is your approach to design systems and reusable components?",
    "How do you measure whether a design change was successful?",
    "Describe a situation where you had to iterate after launch.",
    "How do you handle conflicting opinions from product, engineering, and users?",
    "What makes a strong handoff from design to engineering?",
    "Describe a design challenge where constraints forced a creative solution.",
    "Why is this design role the right fit for you?",
  ],
  Sales: [
    "Tell us about a deal you won and the approach you used.",
    "How do you qualify whether a lead is worth pursuing?",
    "Describe a time you rebuilt trust with a hesitant customer.",
    "How do you handle objections during a sales conversation?",
    "Walk us through how you prepare for an important client meeting.",
    "How do you balance short-term revenue with long-term relationship building?",
    "Describe a time you had to collaborate closely with marketing or product.",
    "How do you keep your pipeline healthy and realistic?",
    "What do you do when a prospect goes quiet late in the process?",
    "Tell us about a time you had to negotiate pricing or scope.",
    "How do you learn the needs of a customer quickly?",
    "Describe a time you missed a target and how you responded.",
    "How do you organize follow-ups without losing momentum?",
    "What signals tell you a deal is likely to close?",
    "How do you adapt your communication style to different buyers?",
    "Describe a time you turned a difficult objection into a win.",
    "How do you use customer feedback to improve your pitch?",
    "What does strong account management look like to you?",
    "Describe your approach to forecasting and reporting.",
    "Why are you excited about this sales role?",
  ],
  Support: [
    "Tell us about a difficult customer issue you resolved.",
    "How do you stay calm when a customer is frustrated or upset?",
    "Describe how you would triage multiple support tickets at once.",
    "How do you balance speed with quality in a support response?",
    "Walk us through how you would investigate an unknown issue.",
    "How do you decide when to escalate an issue to another team?",
    "Describe a time you turned a negative customer interaction into a positive one.",
    "How do you communicate technical details in simple language?",
    "What would you do if you did not know the answer right away?",
    "Tell us about a time you spotted a pattern across customer tickets.",
    "How do you document solutions so the team can reuse them?",
    "Describe a time you improved a support process or workflow.",
    "How do you handle support work when there is a product bug and no fix yet?",
    "What metrics matter most to you in support operations?",
    "How do you keep empathy high when handling repetitive issues?",
    "Describe a time you mentored a teammate or shared knowledge.",
    "How do you keep a customer informed while an issue is still open?",
    "What is your approach to de-escalation and expectation setting?",
    "Describe a support issue that required cross-functional collaboration.",
    "Why does this support role appeal to you?",
  ],
};

const HINDI_QUESTION_BANK: Record<CandidateInterviewRole, string[]> = {
  Engineering: [
    "आपने शुरू से अंत तक बनाए गए किसी सिस्टम और उसमें किए गए trade-offs के बारे में बताइए.",
    "जब production issue की root cause साफ न हो, तो आप उसे कैसे debug करते हैं?",
    "किसी application की performance या scalability सुधारने के अपने अनुभव को समझाइए.",
    "जल्दी ship करने और code quality सुधारने के बीच आप निर्णय कैसे लेते हैं?",
    "किसी technical design को idea से deployment तक lead करने का अनुभव बताइए.",
    "code review में disagreement होने पर आप उसे कैसे संभालते हैं?",
    "feature release के बाद आप कौन से metrics या signals monitor करते हैं?",
    "legacy codebase के साथ काम करने का अपना अनुभव बताइए.",
    "आप अपना code दूसरे engineer के लिए maintainable कैसे बनाते हैं?",
    "किसी कठिन bug को solve करने और fix confirm करने की प्रक्रिया बताइए.",
  ],
  Product: [
    "data और customer feedback के आधार पर लिए गए किसी product decision के बारे में बताइए.",
    "competing feature requests के बीच आप priority कैसे तय करते हैं?",
    "बिना direct authority के stakeholders को influence करने का अनुभव बताइए.",
    "नए product या feature launch की success को आप कैसे define करते हैं?",
    "किसी नए product idea को validate करने की अपनी प्रक्रिया समझाइए.",
    "user needs, business goals, और engineering constraints के बीच balance कैसे बनाते हैं?",
    "नई जानकारी मिलने पर roadmap बदलने का कोई अनुभव बताइए.",
    "किसी flow में users क्यों drop off हो रहे हैं, इसकी investigation आप कैसे करेंगे?",
    "important feature ship करने के बाद आप कौन से metrics track करेंगे?",
    "किसी product experiment के बारे में बताइए जिसने आपकी सोच बदली.",
  ],
  Design: [
    "research से delivery तक own किए गए किसी design project के बारे में बताइए.",
    "user feedback को बेहतर interface में आप कैसे बदलते हैं?",
    "evidence के साथ design decision defend करने का कोई अनुभव बताइए.",
    "visual polish, usability, और speed के बीच balance कैसे बनाते हैं?",
    "किसी messy user problem को solve करने की अपनी process समझाइए.",
    "जब engineering feasibility design बदल देती है, तो आप engineers के साथ कैसे collaborate करते हैं?",
    "usability testing या prototype feedback में आप क्या देखते हैं?",
    "किसी complicated flow को simplify करने का अनुभव बताइए.",
    "अपने daily design work में accessibility के बारे में आप कैसे सोचते हैं?",
    "किसी design के बारे में बताइए जिसने expected से बेहतर perform किया.",
  ],
  Sales: [
    "आपने जीती हुई किसी deal और उसके लिए अपनाए गए approach के बारे में बताइए.",
    "किस lead को pursue करना चाहिए, यह आप कैसे qualify करते हैं?",
    "hesitant customer के साथ trust rebuild करने का अनुभव बताइए.",
    "sales conversation में objections को आप कैसे handle करते हैं?",
    "important client meeting की तैयारी आप कैसे करते हैं?",
    "short-term revenue और long-term relationship building के बीच balance कैसे बनाते हैं?",
    "marketing या product team के साथ closely collaborate करने का अनुभव बताइए.",
    "अपनी pipeline को healthy और realistic कैसे रखते हैं?",
    "process के late stage में prospect silent हो जाए तो आप क्या करते हैं?",
    "pricing या scope negotiation का कोई अनुभव बताइए.",
  ],
  Support: [
    "आपने resolve किए हुए किसी difficult customer issue के बारे में बताइए.",
    "customer frustrated या upset हो तो आप शांत कैसे रहते हैं?",
    "एक साथ multiple support tickets को triage करने की अपनी process बताइए.",
    "support response में speed और quality के बीच balance कैसे बनाते हैं?",
    "unknown issue investigate करने के लिए आप क्या steps लेते हैं?",
    "issue को दूसरी team तक escalate कब करना है, यह कैसे तय करते हैं?",
    "negative customer interaction को positive बनाने का अनुभव बताइए.",
    "technical details को simple language में आप कैसे explain करते हैं?",
    "अगर जवाब तुरंत पता न हो, तो आप क्या करते हैं?",
    "customer tickets में pattern spot करने का कोई अनुभव बताइए.",
  ],
};

const QUESTION_BANK_BY_LANGUAGE: Record<string, Record<CandidateInterviewRole, string[]>> = {
  English: ROLE_QUESTION_BANK,
  Hindi: HINDI_QUESTION_BANK,
  Kannada: {
    Engineering: [
      "ನೀವು ಆರಂಭದಿಂದ ಕೊನೆಯವರೆಗೆ ನಿರ್ಮಿಸಿದ ಒಂದು ವ್ಯವಸ್ಥೆಯ ಬಗ್ಗೆ ಮತ್ತು ನೀವು ತೆಗೆದುಕೊಂಡ ವ್ಯವಹಾರ-ಸಮತೋಲನಗಳ ಬಗ್ಗೆ ಹೇಳಿ.",
      "ಮೂಲ ಕಾರಣ ಸ್ಪಷ್ಟವಾಗಿಲ್ಲದಾಗ ಉತ್ಪಾದನಾ ಸಮಸ್ಯೆಯನ್ನು ನೀವು ಹೇಗೆ ಡೀಬಗ್ ಮಾಡುತ್ತೀರಿ?",
      "ಒಂದು ಅಪ್ಲಿಕೇಶನ್‌ನ ಕಾರ್ಯಕ್ಷಮತೆ ಅಥವಾ ಸ್ಕೇಲಬಿಲಿಟಿಯನ್ನು ನೀವು ಸುಧಾರಿಸಿದ ಸಂದರ್ಭವನ್ನು ವಿವರಿಸಿ.",
      "ಶೀಘ್ರವಾಗಿ ಶಿಪ್ ಮಾಡುವುದಕ್ಕೂ ಕೋಡ್ ಗುಣಮಟ್ಟವನ್ನು ಸುಧಾರಿಸುವುದಕ್ಕೂ ನಡುವೆ ನೀವು ಹೇಗೆ ನಿರ್ಧರಿಸುತ್ತೀರಿ?",
      "ಐಡಿಯಾದಿಂದ ಡಿಪ್ಲಾಯ್‌ಮೆಂಟ್‌ವರೆಗೆ ನೀವು ನೇತೃತ್ವ ವಹಿಸಿದ ತಾಂತ್ರಿಕ ವಿನ್ಯಾಸವನ್ನು ವಿವರಿಸಿ.",
      "ಕೋಡ್ ರಿವ್ಯೂ ಸಮಯದಲ್ಲಿ ಉಂಟಾಗುವ ಭಿನ್ನಾಭಿಪ್ರಾಯಗಳನ್ನು ನೀವು ಹೇಗೆ ನಿಭಾಯಿಸುತ್ತೀರಿ?",
      "ಒಂದು ಫೀಚರ್ ಬಿಡುಗಡೆ ಆದ ನಂತರ ನೀವು ಯಾವ ಮೆಟ್ರಿಕ್‌ಗಳು ಅಥವಾ ಸಿಗ್ನಲ್‌ಗಳನ್ನು ಗಮನಿಸುತ್ತೀರಿ?",
      "ಹಳೆಯ ಕೋಡ್‌ಬೇಸ್‌ನೊಂದಿಗೆ ಕೆಲಸ ಮಾಡಬೇಕಾದ ಸಂದರ್ಭವನ್ನು ವಿವರಿಸಿ.",
      "ನಿಮ್ಮ ಕೋಡ್ ಅನ್ನು ಮತ್ತೊಬ್ಬ ಎಂಜಿನಿಯರ್‌ಗೆ ಸುಲಭವಾಗಿ ನಿರ್ವಹಿಸಬಹುದಾಗಿಸಲು ನೀವು ಏನು ಮಾಡುತ್ತೀರಿ?",
      "ನೀವು ಪರಿಹರಿಸಿದ ಕಷ್ಟಕರ ಬಗ್ ಮತ್ತು ಫಿಕ್ಸ್ ಅನ್ನು ಹೇಗೆ ದೃಢಪಡಿಸಿದಿರಿ ಎಂಬುದನ್ನು ಹೇಳಿ.",
      "ಮಹತ್ವದ ಫೀಚರ್‌ಗಾಗಿ ನೀವು ಪರೀಕ್ಷೆಗಳನ್ನು ಹೇಗೆ ಯೋಜಿಸುತ್ತೀರಿ?",
      "ಹೊಸ ತಂತ್ರಜ್ಞಾನವನ್ನು ಬೇಗ ಕಲಿಯಬೇಕಾದ ಸಂದರ್ಭವನ್ನು ವಿವರಿಸಿ.",
      "ಬಳಕೆದಾರರ ಡೇಟಾ ಮತ್ತು ಸಿಸ್ಟಮ್ ವಿನ್ಯಾಸವನ್ನು ಸುರಕ್ಷಿತವಾಗಿಡಲು ನೀವು ಏನು ಮಾಡುತ್ತೀರಿ?",
      "ಮುಖ್ಯ ಪ್ರಾಜೆಕ್ಟ್‌ನಲ್ಲಿ ಡೆಲಿವರಿ ದಿನಾಂಕ ತಪ್ಪಿದರೆ ನೀವು ಏನು ಮಾಡುತ್ತೀರಿ?",
      "ರಿಕ್ವೈರ್‌ಮೆಂಟ್‌ಗಳ ವಿಷಯದಲ್ಲಿ ಪ್ರಾಡಕ್ಟ್ ಮತ್ತು ಡಿಸೈನ್ ಪಾಲುದಾರರೊಂದಿಗೆ ನೀವು ಹೇಗೆ ಸಹಕರಿಸುತ್ತೀರಿ?",
      "ಅಸ್ಪಷ್ಟ ಸಮಸ್ಯೆಯ ಜವಾಬ್ದಾರಿಯನ್ನು ನೀವು ಹೊತ್ತ ಸಂದರ್ಭವನ್ನು ವಿವರಿಸಿ.",
      "ಸ್ಕೋಪ್ ಪೂರ್ಣವಾಗಿ ತಿಳಿದಿಲ್ಲದಾಗ ಎಂಜಿನಿಯರಿಂಗ್ ಕೆಲಸವನ್ನು ನೀವು ಹೇಗೆ ಅಂದಾಜು ಮಾಡುತ್ತೀರಿ?",
      "ನೀವು observability ಮತ್ತು monitoring ಗೆ ಹೇಗೆ 접근ಿಸುತ್ತೀರಿ?",
      "ಇನ್ನೊಬ್ಬ ಎಂಜಿನಿಯರ್‌ಗೆ ಮಾರ್ಗದರ್ಶನ ನೀಡಬೇಕಾದ ಅಥವಾ ಅವರ ಬ್ಲಾಕರ್ ತೆಗೆದುಹಾಕಬೇಕಾದ ಸಂದರ್ಭವನ್ನು ವಿವರಿಸಿ.",
      "ಈ engineering ಪಾತ್ರವು ನಿಮಗೆ ಮುಂದಿನ ಸೂಕ್ತ ಹೆಜ್ಜೆ ಏಕೆ?",
    ],
    Product: [
      "ಡೇಟಾ ಮತ್ತು ಗ್ರಾಹಕರ ಪ್ರತಿಕ್ರಿಯೆ ಬಳಸಿಕೊಂಡು ನೀವು ಮಾಡಿದ ಪ್ರಾಡಕ್ಟ್ ನಿರ್ಧಾರವನ್ನು ಹೇಳಿ.",
      "ಪರಸ್ಪರ ಸ್ಪರ್ಧಿಸುವ ಫೀಚರ್ ವಿನಂತಿಗಳ ನಡುವೆ ನೀವು ಹೇಗೆ ಆದ್ಯತೆ ನಿಗದಿಪಡಿಸುತ್ತೀರಿ?",
      "ನೇರ ಅಧಿಕಾರವಿಲ್ಲದಿದ್ದರೂ ಸ್ಟೇಕ್‌ಹೋಲ್ಡರ್‌ಗಳ ಮೇಲೆ ಪ್ರಭಾವ ಬೀರುವ ಸಂದರ್ಭವನ್ನು ವಿವರಿಸಿ.",
      "ಹೊಸ ಉತ್ಪನ್ನ ಅಥವಾ ಫೀಚರ್ ಬಿಡುಗಡೆಗೆ ಯಶಸ್ಸನ್ನು ನೀವು ಹೇಗೆ ವ್ಯಾಖ್ಯಾನಿಸುತ್ತೀರಿ?",
      "ಹೊಸ ಪ್ರಾಡಕ್ಟ್ ಐಡಿಯಾವನ್ನು ನೀವು ಹೇಗೆ ಮಾನ್ಯಗೊಳಿಸುತ್ತೀರಿ ಎಂಬುದನ್ನು ವಿವರಿಸಿ.",
      "ಬಳಕೆದಾರರ ಅಗತ್ಯಗಳು, ವ್ಯಾಪಾರದ ಗುರಿಗಳು, ಮತ್ತು engineering ನಿಯಂತ್ರಣಗಳ ನಡುವೆ ನೀವು ಹೇಗೆ ಸಮತೋಲನ ಸಾಧಿಸುತ್ತೀರಿ?",
      "ಹೊಸ ಮಾಹಿತಿ ಬಂದಾಗ ನಿಮ್ಮ roadmap ಅನ್ನು ಬದಲಾಯಿಸಿದ ಸಂದರ್ಭವನ್ನು ವಿವರಿಸಿ.",
      "ಒಂದು flow ನಲ್ಲಿ ಬಳಕೆದಾರರು ಏಕೆ ಹೊರಹೋಗುತ್ತಿದ್ದಾರೆ ಎಂಬುದನ್ನು ನೀವು ಹೇಗೆ ತನಿಖೆ ಮಾಡುತ್ತೀರಿ?",
      "ಒಂದು ಪ್ರಮುಖ ಫೀಚರ್ ಶಿಪ್ ಆದ ನಂತರ ನೀವು ಯಾವ ಮೆಟ್ರಿಕ್‌ಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡುತ್ತೀರಿ?",
      "ನಿಮ್ಮ ಚಿಂತನೆಗೆ ಬದಲಾವಣೆ ತಂದ product experiment ಕುರಿತು ಹೇಳಿ.",
      "ವಿಭಿನ್ನ ತಂಡಗಳಿಂದ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ನೀವು ಹೇಗೆ ಸಂಗ್ರಹಿಸಿ ಸಾರಾಂಶಗೊಳಿಸುತ್ತೀರಿ?",
      "ಒಂದು ವಿನಂತಿಗೆ ಇಲ್ಲ ಎಂದು ಹೇಳಿ ಕಾರಣವನ್ನು ವಿವರಿಸಿದ ಸಂದರ್ಭವನ್ನು ಹೇಳಿ.",
      "ಸಮಸ್ಯೆಯ ವಿವರಣೆ ಸ್ಪಷ್ಟವಾಗಿಲ್ಲದಾಗ ನೀವು ambiguity ಅನ್ನು ಹೇಗೆ ನಿರ್ವಹಿಸುತ್ತೀರಿ?",
      "ಒಂದು product requirement engineering handoff ಗೆ ಸಿದ್ಧವಾಗಿದೆ ಎಂದು ನೀವು ಯಾವಾಗ ಹೇಳುತ್ತೀರಿ?",
      "ಬೆಲೆ ನಿಗದಿ, ಪ್ಯಾಕೇಜಿಂಗ್, ಅಥವಾ monetization trade-offs ಬಗ್ಗೆ ನೀವು ಹೇಗೆ ಯೋಚಿಸುತ್ತೀರಿ?",
      "ನಿರೀಕ್ಷೆಯಂತೆ ಕೆಲಸ ಮಾಡದದ್ದನ್ನು ನೀವು ಶಿಪ್ ಮಾಡಿದ ಸಂದರ್ಭವನ್ನು ವಿವರಿಸಿ.",
      "ಒಂದು ಫೀಚರ್ ಅನ್ನು ಸರಳಗೊಳಿಸಬೇಕೋ ಅಥವಾ ತೆಗೆದುಹಾಕಬೇಕೋ ಎಂದು ನೀವು ಹೇಗೆ ನಿರ್ಧರಿಸುತ್ತೀರಿ?",
      "ಡಿಸೈನ್ ಮತ್ತು engineering ಜೊತೆಗೆ ಬಲವಾದ product partnership ಹೇಗಿರಬೇಕು?",
      "ಮುಂದಿನ ತ್ರೈಮಾಸಿಕದ roadmap ಯೋಜನೆಗೆ ನಿಮ್ಮ ವಿಧಾನವನ್ನು ವಿವರಿಸಿ.",
      "ಈ ಪಾತ್ರದಲ್ಲಿ ಪ್ರಾಡಕ್ಟ್ ಕೆಲಸದ ಬಗ್ಗೆ ನಿಮಗೆ ಆಸಕ್ತಿ ಏಕೆ?",
    ],
    Design: [
      "ಅನ್ವೇಷಣೆಯಿಂದ ಡೆಲಿವರಿ ವರೆಗೆ ನೀವು ಒಡೆತನ ವಹಿಸಿದ design project ಕುರಿತು ಹೇಳಿ.",
      "ಬಳಕೆದಾರರ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ನೀವು ಉತ್ತಮ interface ಆಗಿ ಹೇಗೆ ಪರಿವರ್ತಿಸುತ್ತೀರಿ?",
      "ಸಾಕ್ಷ್ಯಗಳೊಂದಿಗೆ ಒಂದು ವಿನ್ಯಾಸ ನಿರ್ಧಾರವನ್ನು ನೀವು ರಕ್ಷಿಸಿದ ಸಂದರ್ಭವನ್ನು ವಿವರಿಸಿ.",
      "ದೃಶ್ಯ ಮೆರುಗು, ಬಳಕೆಸೌಲಭ್ಯ, ಮತ್ತು ವೇಗದ ನಡುವೆ ನೀವು ಹೇಗೆ ಸಮತೋಲನ ಸಾಧಿಸುತ್ತೀರಿ?",
      "ಗೊಂದಲಯುತ ಬಳಕೆದಾರ ಸಮಸ್ಯೆಯನ್ನು ಪರಿಹರಿಸಲು ನಿಮ್ಮ ಪ್ರಕ್ರಿಯೆಯನ್ನು ವಿವರಿಸಿ.",
      "engineering feasibility ಒಂದು ವಿನ್ಯಾಸವನ್ನು ಬದಲಾಯಿಸಿದಾಗ ನೀವು ಹೇಗೆ ಸಹಕರಿಸುತ್ತೀರಿ?",
      "usability testing ಅಥವಾ prototype feedback ನಲ್ಲಿ ನೀವು ಏನು ಹುಡುಕುತ್ತೀರಿ?",
      "ಒಂದು ಸಂಕೀರ್ಣ flow ಅನ್ನು ನೀವು ಸರಳಗೊಳಿಸಿದ ಸಂದರ್ಭವನ್ನು ವಿವರಿಸಿ.",
      "ನಿಮ್ಮ ದೈನಂದಿನ design ಕೆಲಸದಲ್ಲಿ accessibility ಬಗ್ಗೆ ನೀವು ಹೇಗೆ ಯೋಚಿಸುತ್ತೀರಿ?",
      "ನಿರೀಕ್ಷೆಗಿಂತ ಉತ್ತಮವಾಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸಿದ design ಬಗ್ಗೆ ಹೇಳಿ.",
      "ಪಕ್ವವಾದ ಉತ್ಪನ್ನದಲ್ಲಿ ಮೊದಲು ಏನು ಸರಿಪಡಿಸಬೇಕು ಎಂದು ನೀವು ಹೇಗೆ ನಿರ್ಧರಿಸುತ್ತೀರಿ?",
      "ಕಡಿಮೆ ಮಾಹಿತಿ ಅಥವಾ ಅಸ್ಪಷ್ಟ ಅಗತ್ಯಗಳೊಂದಿಗೆ ಕೆಲಸ ಮಾಡಿದ ಸಂದರ್ಭವನ್ನು ವಿವರಿಸಿ.",
      "ಉತ್ಪನ್ನ ಅನುಭವದಾದ್ಯಂತ consistency ಅನ್ನು ನೀವು ಹೇಗೆ ಕಾಯ್ದುಕೊಳ್ಳುತ್ತೀರಿ?",
      "design systems ಮತ್ತು reusable components ಬಗ್ಗೆ ನಿಮ್ಮ ವಿಧಾನವೇನು?",
      "ಒಂದು design change ಯಶಸ್ವಿಯಾಯಿತೇ ಎಂದು ನೀವು ಹೇಗೆ ಅಳೆಯುತ್ತೀರಿ?",
      "launch ನಂತರ iteration ಅಗತ್ಯವಾದ ಸಂದರ್ಭವನ್ನು ವಿವರಿಸಿ.",
      "product, engineering, ಮತ್ತು ಬಳಕೆದಾರರಿಂದ ಬರುವ ವಿರುದ್ಧ ಅಭಿಪ್ರಾಯಗಳನ್ನು ನೀವು ಹೇಗೆ ನಿಭಾಯಿಸುತ್ತೀರಿ?",
      "design ನಿಂದ engineering ಗೆ ಉತ್ತಮ handoff ಹೇಗಿರಬೇಕು?",
      "ನಿಯಂತ್ರಣಗಳು creative solution ಗೆ ಒತ್ತಾಯಿಸಿದ design challenge ಅನ್ನು ವಿವರಿಸಿ.",
      "ಈ design ಪಾತ್ರವು ನಿಮಗೆ ಸೂಕ್ತವಾಗಿದೆ ಎಂದು ನೀವು ಏಕೆ ಭಾವಿಸುತ್ತೀರಿ?",
    ],
    Sales: [
      "ನೀವು ಗೆದ್ದ ಒಂದು deal ಮತ್ತು ಅದಕ್ಕಾಗಿ ಬಳಸಿದ ನಿಮ್ಮ ವಿಧಾನವನ್ನು ಹೇಳಿ.",
      "ಯಾವ lead ಮುಂದುವರಿಸಲು ಅರ್ಹವಾಗಿದೆ ಎಂದು ನೀವು ಹೇಗೆ ನಿರ್ಣಯಿಸುತ್ತೀರಿ?",
      "ಸಂಕೋಚಗೊಂಡ customer ನ ನಂಬಿಕೆಯನ್ನು ನೀವು ಮರು ನಿರ್ಮಿಸಿದ ಸಂದರ್ಭವನ್ನು ವಿವರಿಸಿ.",
      "sales ಸಂಭಾಷಣೆಯಲ್ಲಿ objection ಗಳನ್ನು ನೀವು ಹೇಗೆ ನಿಭಾಯಿಸುತ್ತೀರಿ?",
      "ಮುಖ್ಯ client meeting ಗೆ ನೀವು ಹೇಗೆ ತಯಾರಿ ಮಾಡಿಕೊಳ್ಳುತ್ತೀರಿ ಎಂಬುದನ್ನು ವಿವರಿಸಿ.",
      "ಕಾಲಕಾಲಕ್ಕೆ ಬರುವ revenue ಮತ್ತು ದೀರ್ಘಕಾಲದ ಸಂಬಂಧ ನಿರ್ಮಾಣದ ನಡುವೆ ನೀವು ಹೇಗೆ ಸಮತೋಲನ ಸಾಧಿಸುತ್ತೀರಿ?",
      "marketing ಅಥವಾ product ಜೊತೆ ನಿಕಟವಾಗಿ ಸಹಕರಿಸಿದ ಸಂದರ್ಭವನ್ನು ವಿವರಿಸಿ.",
      "ನಿಮ್ಮ pipeline ಅನ್ನು ಆರೋಗ್ಯಕರವಾಗಿಯೂ ಯಥಾರ್ಥವಾಗಿಯೂ ನೀವು ಹೇಗೆ ಉಳಿಸುತ್ತೀರಿ?",
      "ಪ್ರಕ್ರಿಯೆಯ ಕೊನೆಯಲ್ಲಿ prospect ಮೌನವಾಗಿದಾಗ ನೀವು ಏನು ಮಾಡುತ್ತೀರಿ?",
      "ಬೆಲೆ ಅಥವಾ scope ಕುರಿತು ಮಾತುಕತೆ ಮಾಡಿದ ಸಂದರ್ಭವನ್ನು ಹೇಳಿ.",
      "ಗ್ರಾಹಕರ ಅಗತ್ಯಗಳನ್ನು ನೀವು ಬೇಗನೆ ಹೇಗೆ ತಿಳಿದುಕೊಳ್ಳುತ್ತೀರಿ?",
      "ನೀವು target ತಪ್ಪಿಸಿದ ಸಂದರ್ಭ ಮತ್ತು ಅದಕ್ಕೆ ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ವಿವರಿಸಿ.",
      "ಅನುಸರಣೆಗಳನ್ನು momentum ಕಳೆದುಕೊಳ್ಳದೆ ನೀವು ಹೇಗೆ ಆಯೋಜಿಸುತ್ತೀರಿ?",
      "ಒಂದು deal ಮುಗಿಯುವ ಸಾಧ್ಯತೆ ಇದೆ ಎಂದು ಯಾವ ಸೂಚನೆಗಳು ಹೇಳುತ್ತವೆ?",
      "ವಿಭಿನ್ನ ಖರೀದಿದಾರರಿಗೆ ನಿಮ್ಮ ಸಂವಹನ ಶೈಲಿಯನ್ನು ನೀವು ಹೇಗೆ ಹೊಂದಿಸುತ್ತೀರಿ?",
      "ಕಠಿಣ objection ಅನ್ನು ಜಯವಾಗಿ ಪರಿವರ್ತಿಸಿದ ಸಂದರ್ಭವನ್ನು ವಿವರಿಸಿ.",
      "ಗ್ರಾಹಕರ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ನಿಮ್ಮ pitch ಅನ್ನು ಉತ್ತಮಗೊಳಿಸಲು ನೀವು ಹೇಗೆ ಬಳಸುತ್ತೀರಿ?",
      "ಬಲವಾದ account management ಹೇಗಿರಬೇಕು?",
      "forecasting ಮತ್ತು reporting ಕುರಿತು ನಿಮ್ಮ ವಿಧಾನವನ್ನು ವಿವರಿಸಿ.",
      "ಈ sales ಪಾತ್ರದ ಬಗ್ಗೆ ನೀವು ಉತ್ಸಾಹ ಹೊಂದಿರುವುದು ಏಕೆ?",
    ],
    Support: [
      "ನೀವು ಪರಿಹರಿಸಿದ ಕಷ್ಟಕರ customer issue ಬಗ್ಗೆ ಹೇಳಿ.",
      "ಗ್ರಾಹಕರು ನಿರಾಶರಾಗಿದ್ದಾಗ ಅಥವಾ ಕೋಪಗೊಂಡಾಗ ನೀವು ಹೇಗೆ ಶಾಂತವಾಗಿರುತ್ತೀರಿ?",
      "ಒಂದೇ ಸಮಯದಲ್ಲಿ ಹಲವು support tickets ಗಳನ್ನು ನೀವು ಹೇಗೆ triage ಮಾಡುತ್ತೀರಿ?",
      "support response ನಲ್ಲಿ ವೇಗ ಮತ್ತು ಗುಣಮಟ್ಟದ ನಡುವೆ ನೀವು ಹೇಗೆ ಸಮತೋಲನ ಸಾಧಿಸುತ್ತೀರಿ?",
      "ಅಪರಿಚಿತ issue ಅನ್ನು ನೀವು ಹೇಗೆ ತನಿಖೆ ಮಾಡುತ್ತೀರಿ ಎಂಬುದನ್ನು ವಿವರಿಸಿ.",
      "ಯಾವಾಗ issue ಅನ್ನು ಇನ್ನೊಂದು ತಂಡಕ್ಕೆ escalate ಮಾಡಬೇಕು ಎಂದು ನೀವು ಹೇಗೆ ನಿರ್ಧರಿಸುತ್ತೀರಿ?",
      "ನಕಾರಾತ್ಮಕ customer interaction ಅನ್ನು ಸಕಾರಾತ್ಮಕವಾಗಿಸಿದ ಸಂದರ್ಭವನ್ನು ವಿವರಿಸಿ.",
      "ತಾಂತ್ರಿಕ ವಿವರಗಳನ್ನು ಸರಳ ಭಾಷೆಯಲ್ಲಿ ನೀವು ಹೇಗೆ ಹೇಳುತ್ತೀರಿ?",
      "ಉತ್ತರ ತಕ್ಷಣ ಗೊತ್ತಿಲ್ಲದಿದ್ದರೆ ನೀವು ಏನು ಮಾಡುತ್ತೀರಿ?",
      "ಗ್ರಾಹಕ tickets ಗಳಲ್ಲಿ ಮಾದರಿಯನ್ನು ಗಮನಿಸಿದ ಸಂದರ್ಭವನ್ನು ಹೇಳಿ.",
      "ತಂಡ ಮರುಬಳಕೆ ಮಾಡಿಕೊಳ್ಳಲು ಪರಿಹಾರಗಳನ್ನು ನೀವು ಹೇಗೆ ದಾಖಲಿಸುತ್ತೀರಿ?",
      "support process ಅಥವಾ workflow ಅನ್ನು ನೀವು ಸುಧಾರಿಸಿದ ಸಂದರ್ಭವನ್ನು ವಿವರಿಸಿ.",
      "ಒಂದು product bug ಇರುತ್ತದೆ ಮತ್ತು ಇನ್ನೂ fix ಇಲ್ಲದಾಗ support ಕೆಲಸವನ್ನು ನೀವು ಹೇಗೆ ನಿಭಾಯಿಸುತ್ತೀರಿ?",
      "support operations ನಲ್ಲಿ ನಿಮಗೆ ಅತ್ಯಂತ ಮುಖ್ಯವಾದ metrics ಯಾವುವು?",
      "ಪುನರಾವರ್ತನೆಯ ಸಮಸ್ಯೆಗಳನ್ನು ನಿಭಾಯಿಸುವಾಗ empathy ಅನ್ನು ನೀವು ಹೇಗೆ ಉಳಿಸುತ್ತೀರಿ?",
      "ತಂಡದ ಜೊತೆ knowledge ಹಂಚಿಕೊಂಡ ಅಥವಾ teammate ಗೆ ಮಾರ್ಗದರ್ಶನ ನೀಡಿದ ಸಂದರ್ಭವನ್ನು ವಿವರಿಸಿ.",
      "issue ಇನ್ನೂ ತೆರೆದಿದ್ದಾಗ ಗ್ರಾಹಕರಿಗೆ ಮಾಹಿತಿ ನೀಡುವುದನ್ನು ನೀವು ಹೇಗೆ ಮುಂದುವರಿಸುತ್ತೀರಿ?",
      "de-escalation ಮತ್ತು expectation setting ಕುರಿತು ನಿಮ್ಮ ವಿಧಾನ ಏನು?",
      "cross-functional collaboration ಬೇಕಾದ support issue ಅನ್ನು ವಿವರಿಸಿ.",
      "ಈ support ಪಾತ್ರ ನಿಮಗೆ ಆಕರ್ಷಕವಾಗಿರುವುದು ಏಕೆ?",
    ],
  },
};

export const SUPPORTED_INTERVIEW_LANGUAGES = ["English", "Hindi", "Kannada"] as const;

export function getInterviewQuestionBank(role: CandidateInterviewRole, language: string) {
  return QUESTION_BANK_BY_LANGUAGE[language]?.[role] ?? ROLE_QUESTION_BANK[role];
}

export function selectRandomInterviewQuestions(
  role: CandidateInterviewRole,
  language: string,
  count = 5,
): InterviewQuestion[] {
  const bank = [...getInterviewQuestionBank(role, language)];
  const selected: InterviewQuestion[] = [];
  while (bank.length > 0 && selected.length < count) {
    const index = Math.floor(Math.random() * bank.length);
    const [question] = bank.splice(index, 1);
    selected.push({ questionIndex: selected.length, question });
  }
  return selected;
}

export function getSpeechLanguage(language: string) {
  if (language === "Hindi") return "hi-IN";
  if (language === "Kannada") return "kn-IN";
  return "en-US";
}

export function getPreferredRecordingMimeType() {
  if (typeof MediaRecorder === "undefined") return "";

  const candidates = [
    "video/mp4;codecs=h264,aac",
    "video/mp4;codecs=avc1.42E01E,mp4a.40.2",
    "video/mp4",
    "video/webm;codecs=vp9,opus",
    "video/webm;codecs=vp8,opus",
    "video/webm",
  ];

  return candidates.find((mimeType) => MediaRecorder.isTypeSupported(mimeType)) ?? "video/webm";
}
